# -*- coding: utf-8 -*-
"""TrabalhoM1-Gabriel,Eduardo-IA.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1J8YtCq58of4zCRv4XCiDZBJ36o8PPG7X

Alunos: Gabriel Schaldach Morgado, Eduardo Lechinski Ramos

Trabalho M1 - Inteligência Artificial

Encaminhamento: https://docs.google.com/document/d/1Cl0L9yJN01gSwmXidKAYI-Bkn9OiiUAO4svEbbnruaE/edit?usp=sharing

Documentação dataset: https://archive.ics.uci.edu/dataset/602/dry+bean+dataset

https://developers.google.com/machine-learning/crash-course/overfitting/imbalanced-datasets?hl=pt-br

link do overleaf: https://www.overleaf.com/6897273326jxpwvnjfcgzv#503319

streamlit: https://m1ai-uni.streamlit.app/

# 1. Análise Exploratória de Dados (AED)

## 1.1 Inspeção inicial
"""

### Instalando pacote do dataset (código fornecido)
!pip install ucimlrepo

# Importando pacotes principais

import numpy as np
import seaborn as sns
import pandas as pd
import matplotlib.pyplot as plt
import joblib
import tensorflow as tf
from tensorflow import keras
from tensorflow.keras import layers, callbacks, initializers

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler, LabelEncoder
from sklearn.metrics import (
    classification_report,
    confusion_matrix,
    accuracy_score,
    f1_score,
)
from sklearn.utils.class_weight import compute_class_weight
from ucimlrepo import fetch_ucirepo

# fetch dataset
dry_bean = fetch_ucirepo(id=602)

# data (as pandas dataframes)
X = dry_bean.data.features
y = dry_bean.data.targets

# metadata
print(dry_bean.metadata)

# variable information
print(dry_bean.variables)

# Observando classes alvo
y.value_counts()

# Verificando tamanho do dataset
y.shape

X.shape

## 1.2 Verificação e remoção de duplicatas
"""

# Verificando registros duplicados
X.duplicated().sum()

pd.concat([X, y], axis = 1).duplicated().sum()

X.columns

"""## 1.3 Distribuição das features"""

# Fazendo histograma
X.hist(figsize = (15,12))

# Fazendo histogramas com transformação logarítmica
X.transform(np.log).hist(figsize = (15,12))

"""## 1.4 Análise e correlação de Pearson"""

sns.heatmap(X.corr())

X.corr()

"""## 1.5 Boxplots por classe"""

fig, axes = plt.subplots(3,2,sharex=False,sharey=False, figsize = (15,18))

pd.concat([X, y], axis = 1).boxplot(column = ["Area", "Eccentricity", "Roundness", "ShapeFactor1", "MajorAxisLength", "Extent"], by = "Class", ax = axes)

"""# 2. Pré-processamento

## 2.1. Codificação da variável alvo
"""

le = LabelEncoder()
y_encoded = le.fit_transform(y)
y_encoded

"""## 2.2 Normalização das features"""

scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)
X_scaled

"""## 2.3 Tratamento do desbalanceamento com class_weight"""

classes_unicas = np.unique(y_encoded)
pesos = compute_class_weight(
    class_weight="balanced", classes=classes_unicas, y=y_encoded
)
class_weight_dict = dict(zip(classes_unicas, pesos))

print("Pesos por classe (balanced):")
for idx, nome in enumerate(le.classes_):
    print(f"  {nome:12s} (índice {idx}): {class_weight_dict[idx]:.4f}")

"""## 2.4 Divisão treino / validação / teste"""

X_arr = X.values

# 1ª divisão: 80 % treino+val  /  20 % teste
X_trainval, X_test_raw, y_trainval, y_test = train_test_split(
    X_arr, y_encoded, test_size=0.20, random_state=42, stratify=y_encoded
)

# 2ª divisão: 75 % treino  /  25 % validação (do conjunto de 80 %)
# → resulta em 60 % treino e 20 % validação do total
X_train_raw, X_val_raw, y_train, y_val = train_test_split(
    X_trainval, y_trainval, test_size=0.25, random_state=42, stratify=y_trainval
)

print(f"Treino    : {X_train_raw.shape[0]} amostras")
print(f"Validação : {X_val_raw.shape[0]} amostras")
print(f"Teste     : {X_test_raw.shape[0]} amostras")


scaler_final = StandardScaler()
X_train = scaler_final.fit_transform(X_train_raw)
X_val = scaler_final.transform(X_val_raw)
X_test = scaler_final.transform(X_test_raw)

"""# 3. Construção, treinamento e experimentos"""

colunas = list(X.columns)
features_sel = [
    "Area",
    "MajorAxisLength",
    "MinorAxisLength",
    "AspectRatio",
    "Eccentricity",
    "Extent",
    "Solidity",
    "Roundness",
    "Compactness",
    "ShapeFactor1",
    "ShapeFactor2",
    "ShapeFactor4",
]
idx_sel = [colunas.index(f) for f in features_sel]

X_train_sel = X_train[:, idx_sel]
X_val_sel = X_val[:, idx_sel]
X_test_sel = X_test[:, idx_sel]

nomes_classes = list(le.classes_)
N_CLASSES = len(nomes_classes)

"""## Helpers

"""

def construir_modelo(
    n_entrada, unidades, taxas_dropout, inicializador="he_normal", lr=1e-3
):
    modelo = keras.Sequential()
    modelo.add(layers.Input(shape=(n_entrada,)))
    for u, d in zip(unidades, taxas_dropout):
        modelo.add(layers.Dense(u, activation="relu", kernel_initializer=inicializador))
        if d is not None and d > 0:
            modelo.add(layers.Dropout(d))
    modelo.add(layers.Dense(N_CLASSES, activation="softmax"))

    modelo.compile(
        optimizer=keras.optimizers.Adam(learning_rate=lr),
        loss="sparse_categorical_crossentropy",
        metrics=["accuracy"],
    )
    return modelo


def treinar(modelo, X_tr, y_tr, X_v, y_v, batch_size=64, epocas=300, usar_pesos=False):
    cb_early = callbacks.EarlyStopping(
        monitor="val_loss", patience=10, restore_best_weights=True
    )
    pesos = class_weight_dict if usar_pesos else None

    historico = modelo.fit(
        X_tr,
        y_tr,
        validation_data=(X_v, y_v),
        epochs=epocas,
        batch_size=batch_size,
        callbacks=[cb_early],
        class_weight=pesos,
        verbose=0,
    )
    return historico

# IA generativa para gerar plots *
def plotar_curvas(historico, titulo):
    fig, axes = plt.subplots(1, 2, figsize=(14, 5))

    axes[0].plot(historico.history["loss"], label="treino")
    axes[0].plot(historico.history["val_loss"], label="validação")
    axes[0].set_title(f"{titulo} — Loss")
    axes[0].set_xlabel("Época")
    axes[0].set_ylabel("Loss")
    axes[0].legend()

    axes[1].plot(historico.history["accuracy"], label="treino")
    axes[1].plot(historico.history["val_accuracy"], label="validação")
    axes[1].set_title(f"{titulo} — Acurácia")
    axes[1].set_xlabel("Época")
    axes[1].set_ylabel("Acurácia")
    axes[1].legend()

    plt.tight_layout()
    plt.show()


def avaliar(modelo, X_te, y_te):
    y_pred = modelo.predict(X_te, verbose=0).argmax(axis=1)
    acc = accuracy_score(y_te, y_pred)
    f1m = f1_score(y_te, y_pred, average="macro")
    print(f"  Acurácia  : {acc:.4f}")
    print(f"  F1-macro  : {f1m:.4f}")
    print()
    print(classification_report(y_te, y_pred, target_names=nomes_classes))
    return acc, f1m, y_pred


resultados = []

"""## Experimento A — Sem Dropout (referência)"""

tf.random.set_seed(42)
modelo_A = construir_modelo(
    n_entrada=X_train.shape[1],
    unidades=[128, 64],
    taxas_dropout=[None, None],
)
historico_A = treinar(modelo_A, X_train, y_train, X_val, y_val, usar_pesos=False)
plotar_curvas(historico_A, "Experimento A — Sem Dropout")

print("=== Experimento A — Sem Dropout ===")
acc_A, f1_A, _ = avaliar(modelo_A, X_test, y_test)

"""## Experimento A2 — Com Dropout"""

tf.random.set_seed(42)
modelo_A2 = construir_modelo(
    n_entrada=X_train.shape[1], unidades=[128, 64], taxas_dropout=[0.3, 0.2]
)
historico_A2 = treinar(modelo_A2, X_train, y_train, X_val, y_val, usar_pesos=False)
plotar_curvas(historico_A2, "Experimento A2 — Com Dropout")

print("=== Experimento A2 — Com Dropout ===")
acc_A2, f1_A2, _ = avaliar(modelo_A2, X_test, y_test)

"""## Experimento B — class_weight"""

tf.random.set_seed(42)
modelo_B = construir_modelo(
    n_entrada=X_train.shape[1], unidades=[128, 64], taxas_dropout=[0.3, 0.2]
)
historico_B = treinar(
    modelo_B, X_train, y_train, X_val, y_val, usar_pesos=True
)
plotar_curvas(historico_B, "Experimento B — class_weight")

print("=== Experimento B — class_weight ===")
acc_B, f1_B, _ = avaliar(modelo_B, X_test, y_test)

"""## Experimento C — Rede maior (3 camadas ocultas)"""

tf.random.set_seed(42)
modelo_C = construir_modelo(
    n_entrada=X_train.shape[1], unidades=[256, 128, 64], taxas_dropout=[0.3, 0.3, 0.2]
)
historico_C = treinar(modelo_C, X_train, y_train, X_val, y_val, usar_pesos=True)
plotar_curvas(historico_C, "Experimento C — Rede Maior (3 camadas)")

print("=== Experimento C — Rede Maior ===")
acc_C, f1_C, _ = avaliar(modelo_C, X_test, y_test)

"""## Experimento D — Inicializador diferente"""

#uso de IA generativa para plots*

tf.random.set_seed(42)
modelo_D1 = construir_modelo(
    n_entrada=X_train.shape[1],
    unidades=[128, 64],
    taxas_dropout=[0.3, 0.2],
    inicializador="he_normal",
)
historico_D1 = treinar(modelo_D1, X_train, y_train, X_val, y_val, usar_pesos=True)


tf.random.set_seed(42)
modelo_D2 = construir_modelo(
    n_entrada=X_train.shape[1],
    unidades=[128, 64],
    taxas_dropout=[0.3, 0.2],
    inicializador=initializers.RandomNormal(mean=0.0, stddev=0.05),
)
historico_D2 = treinar(modelo_D2, X_train, y_train, X_val, y_val, usar_pesos=True)


epocas_plot = min(
    30, len(historico_D1.history["loss"]), len(historico_D2.history["loss"])
)
fig, axes = plt.subplots(1, 2, figsize=(14, 5))
axes[0].plot(historico_D1.history["loss"][:epocas_plot], label="he_normal — treino")
axes[0].plot(historico_D1.history["val_loss"][:epocas_plot], label="he_normal — val")
axes[0].plot(
    historico_D2.history["loss"][:epocas_plot],
    label="RandomNormal — treino",
    linestyle="--",
)
axes[0].plot(
    historico_D2.history["val_loss"][:epocas_plot],
    label="RandomNormal — val",
    linestyle="--",
)
axes[0].set_title("Exp D — Loss (primeiras épocas)")
axes[0].set_xlabel("Época")
axes[0].set_ylabel("Loss")
axes[0].legend()

axes[1].plot(historico_D1.history["accuracy"][:epocas_plot], label="he_normal — treino")
axes[1].plot(
    historico_D1.history["val_accuracy"][:epocas_plot], label="he_normal — val"
)
axes[1].plot(
    historico_D2.history["accuracy"][:epocas_plot],
    label="RandomNormal — treino",
    linestyle="--",
)
axes[1].plot(
    historico_D2.history["val_accuracy"][:epocas_plot],
    label="RandomNormal — val",
    linestyle="--",
)
axes[1].set_title("Exp D — Acurácia (primeiras épocas)")
axes[1].set_xlabel("Época")
axes[1].set_ylabel("Acurácia")
axes[1].legend()
plt.tight_layout()
plt.show()

print("=== Experimento D1 — he_normal ===")
acc_D1, f1_D1, _ = avaliar(modelo_D1, X_test, y_test)
print("=== Experimento D2 — RandomNormal ===")
acc_D2, f1_D2, _ = avaliar(modelo_D2, X_test, y_test)

"""## Experimento E — Features selecionadas na AED"""

tf.random.set_seed(42)
modelo_E = construir_modelo(
    n_entrada=X_train_sel.shape[1],
    unidades=[128, 64],
    taxas_dropout=[0.3, 0.2],
)
historico_E = treinar(modelo_E, X_train_sel, y_train, X_val_sel, y_val, usar_pesos=True)
plotar_curvas(historico_E, "Experimento E — Features Selecionadas")

print("=== Experimento E — Features selecionadas ===")
acc_E, f1_E, y_pred_E = avaliar(modelo_E, X_test_sel, y_test)

"""## Experimento F — Melhor configuração
Justificativa das escolhas:
  - 3 camadas ocultas [256-128-64]: se mostrou muito bom em relação a loss no experimento C
  - Dropout escalonado [0.3, 0.2, 0.1]: escalando por neoronio e camada [256, 128, 64].
  - class_weight=True: essencial para não ignorar BOMBAY e BARBUNYA.
  - lr=5e-4: aprendizado mais leve para evitar saltos (dataset não tão grande).
  - batch_size=128: melhor resultado de equilibrio em testes.
  - Todas as 16 features: experimentos D1 e E mostraram que remover
    features não trouxe muito ganho.
"""

tf.random.set_seed(42)
modelo_F = construir_modelo(
    n_entrada=X_train.shape[1],
    unidades=[256, 128, 64],
    taxas_dropout=[0.3, 0.2, 0.1],
    lr=5e-4,
)
historico_F = treinar(
    modelo_F, X_train, y_train, X_val, y_val, batch_size=128, usar_pesos=True
)
plotar_curvas(historico_F, "Experimento F — Melhor Configuração")

print("=== Experimento F — Melhor configuração ===")
acc_F, f1_F, y_pred_F = avaliar(modelo_F, X_test, y_test)

cm = confusion_matrix(y_test, y_pred_F)

plt.figure(figsize=(10, 8))
sns.heatmap(
    cm,
    annot=True,
    fmt="d",
    cmap="Blues",
    xticklabels=nomes_classes,
    yticklabels=nomes_classes,
)
plt.title("Matriz de Confusão — Experimento F (Melhor Modelo)")
plt.xlabel("Classe Prevista")
plt.ylabel("Classe Real")
plt.tight_layout()
plt.show()

# cm = confusion_matrix(y_test, y_pred_E)

# plt.figure(figsize=(10, 8))
# sns.heatmap(
#     cm,
#     annot=True,
#     fmt="d",
#     cmap="Blues",
#     xticklabels=nomes_classes,
#     yticklabels=nomes_classes,
# )
# plt.title("Matriz de Confusão — Experimento E")
# plt.xlabel("Classe Prevista")
# plt.ylabel("Classe Real")
# plt.tight_layout()
# plt.show()

import joblib
# https://keras.io/api/callbacks/model_checkpoint/
CAMINHO_MODELO = "melhor_modelo.keras"
CAMINHO_SCALER = "scaler_final.pkl"
CAMINHO_ENCODER = "label_encoder.pkl"

tf.random.set_seed(42)
modelo_final = construir_modelo(
    n_entrada=X_train.shape[1],
    unidades=[256, 128, 64],
    taxas_dropout=[0.3, 0.2, 0.1],
    lr=5e-4,
)

cb_checkpoint = callbacks.ModelCheckpoint(
    filepath=CAMINHO_MODELO, monitor="val_loss", save_best_only=True, verbose=1
)
cb_early = callbacks.EarlyStopping(
    monitor="val_loss", patience=10, restore_best_weights=True
)

modelo_final.fit(
    X_train,
    y_train,
    validation_data=(X_val, y_val),
    epochs=300,
    batch_size=128,
    callbacks=[cb_checkpoint, cb_early],
    class_weight=class_weight_dict,
    verbose=1,
)

# scales e label encoder é só estruturas basicas de python, só precisamos usar pkl
joblib.dump(scaler_final, CAMINHO_SCALER)
joblib.dump(le, CAMINHO_ENCODER)

# streamlit

import streamlit as st
import numpy as np
import joblib
import tensorflow as tf
import matplotlib.pyplot as plt

CAMINHO_MODELO = "melhor_modelo.keras"
CAMINHO_SCALER = "scaler_final.pkl"
CAMINHO_ENCODER = "label_encoder.pkl"


@st.cache_resource
def carregar_modelo():
    modelo = tf.keras.models.load_model(CAMINHO_MODELO)
    scaler = joblib.load(CAMINHO_SCALER)
    encoder = joblib.load(CAMINHO_ENCODER)
    return modelo, scaler, encoder


modelo, scaler, encoder = carregar_modelo()

st.title("Classificador com Rede Neural")

st.write("Insira os valores das features:")


feature_names = [
    "Area",
    "Perimeter",
    "MajorAxisLength",
    "MinorAxisLength",
    "AspectRatio",
    "Eccentricity",
    "ConvexArea",
    "EquivDiameter",
    "Extent",
    "Solidity",
    "Roundness",
    "Compactness",
    "ShapeFactor1",
    "ShapeFactor2",
    "ShapeFactor3",
    "ShapeFactor4",
]

inputs = []


for i, feature in enumerate(feature_names):
    val = st.number_input(feature, value=0.0)
    inputs.append(val)

entrada = np.array(inputs).reshape(1, -1)

if st.button("Prever"):
    entrada_scaled = scaler.transform(entrada)

    probs = modelo.predict(entrada_scaled)[0]
    classe_idx = np.argmax(probs)
    classe_nome = encoder.inverse_transform([classe_idx])[0]

    st.subheader(f"Classe prevista: {classe_nome}")

    fig, ax = plt.subplots()
    ax.bar(encoder.classes_, probs)
    ax.set_ylabel("Probabilidade")
    ax.set_xlabel("Classe")
    ax.set_title("Distribuição de Probabilidades")

    st.pyplot(fig)
